export const errorCodes = {
    "AUTH": {
        'PAY001': 'Missing Required fields to generate auth token.',
        'PAY003': 'Authorization Failed. Missing Bearer Token',
        'PAY004': 'Authorization Failed. Invalid Bearer Token',
        'PAY006': 'Empty Request Body. No Fields Found',
        'PAY008': 'Missing keyword "Bearer" in the Authorization',
        'PAY012': 'Email Not Found. Unable to Login',
        'PAY032': 'Login Successful. But User is not active',
        'PAY013': 'Incorrect Email and Password. Unable to Login'
    },
    "BANK": {
        'PAY084': 'Missing Mandatory Fields while Fetching Bank Details by User',
        'PAY085': 'Missing Mandatory Fields while Inserting Bank Details by User',
        'PAY086': 'Missing Mandatory Fields while Removing Bank Details',
        'PAY087': 'Error while Removing Bank Account',
        'PAY088': 'Error while Creating Bank Account',
        'PAY089': 'Error while Creating Stripe Account',
        'PAY090': 'Bank Accounts Fetched Successfully',
        'PAY091': 'Bank Information Fetched Successfully',
        'PAY092': 'Bank Information Removed Successfully'
    },
    "STRIPE": {
        'PAY081': 'Missing Mandatory Fields while Generating Stripe Key',
        'PAY082': 'Missing Mandatory Fields while Fetching Stripe Accounts by Escrow',
        'PAY083': 'Payment is in Progress. Please Submit after Sometime',
        'PAY084': 'Account has been Updated. Please Submit after Sometime'
    },
    "MESSAGE": {
        'PAY074': 'Missing Mandatory Fields while Inserting Messages',
        'PAY075': 'Missing Mandatory Fields while Getting Message By Escrow',
        'PAY076': 'Missing Mandatory Fields while Deleting Message',
        'PAY077': 'Error while Inserting the Message',
        'PAY078': 'Error while Deleting the Message',
        'PAY079': 'Missing Mandatory Fields while fetching Message User'
    },
    "USER": {
        'PAY002': 'Error Generating Code. Please refer Error Message.',
        'PAY005': 'Missing Mandatory Fields in User Creation',
        'PAY007': 'Failed.Unable to Create a User',
        'PAY009': 'Error Fetching User list',
        'PAY010': 'Email already exists in the System',
        'PAY011': 'Missing Mandatory Fields in User Login',
        'PAY012': 'Email Not Found. Unable to Login',
        'PAY014': 'Error in Creating Token after Successful Login',
        'PAY015': 'Error in Creating User. Unable to get User ID',
        'PAY016': 'Error in Creating User. Unable to generate OTP',
        'PAY017': 'Missing Required fields for activating User through OTP',
        'PAY018': 'MisMatch OTP Information',
        'PAY019': 'Error. Unable to activate the User',
        'PAY020': 'Missing Required Fields for Forget Password',
        'PAY021': 'Error in Generating Password',
        'PAY022': 'Error in Generating Password. Invalid Email',
        'PAY023': 'Missing Required Fields for fetching User Id',
        'PAY024': 'Invalid User Id from Get User',
        'PAY025': 'Missing or Invalid Fields at Update User',
        'PAY026': 'Update Failed. Invalid User Id',
        'PAY027': 'Update Failed. Email Already Existing in the system',
        'PAY028': 'Required Fields are missing',
        'PAY029': 'Duplicate User Id Triggered through params as well as in the Bearer Token',
        'PAY030': 'Missing Mandatory Fields in Generate OTP Service',
        'PAY033': 'Unable to activate the User. OTP Mismatch',
        'PAY064': 'User not found for a given email information',
        'PAY045': 'Error while fetching Buyer User Details',
        'PAY046': 'Error while fetching Seller User Details',
        'PAY080': 'Error while Fetching the User by Message',
        'PAY063': 'Missing Mandatory Fields while fetching Information By Email',
        'PAY064': 'OTP Regnerated Successfully. Please check your mail',
        'PAY065': 'Password generated Successfully. Please check your registered Email',
        'PAY066': 'Password reset has completed successfully'
    },
    "FILE": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while Remove',
        '015': 'Unable to find the attachment',
        '007': 'File Saved successfully',
        '008': 'Problem while saving and creating a file',
        '009': 'File has been fetched successfully',
        '010': 'Unable to fetch a file',
        '013': 'File has been removed successfully',
        '014': 'Unable to delete the file',
        '015': 'File Content Not Found',
        '016': 'Unable to save the KYC in Stripe'
    },
    "FILECONNECT": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while Remove',
        '004': 'Missing Mandatory Fields while File Connect',
        '007': 'File Saved successfully',
        '008': 'Problem while saving and creating a file',
        '009': 'File has been fetched successfully',
        '010': 'Unable to fetch a file',
        '013': 'File has been removed successfully',
        '014': 'Unable to delete the file',
        '015': 'File has been fetched successfully',
        '016': 'Unable to fetch connect file'
    },
    "PRODUCT": {
        '001': 'Missing Mandate Fields to Insert',
        '002': 'Missing Mandate Fields to Get',
        '003': 'Missing Mandate Fields to List',
        '004': 'Missing Mandate Fields to Fetch By Companies',
        '005': 'Missing Mandate Fields to Remove',
        '007' : 'Product Inserted Successfully',
        '008' : 'Unable to Insert Category',
        '009' : 'Product Fetched Successfully',
        '010' : 'Unable to Fetch Product',
        '011' : 'Product Fetched by Company Info',
        '012' : 'Unable to fetch Product by Company Info',
        '013' : 'Product Removed Successfully',
        '014' : 'Unable to Remove Product',
        '015' : 'Product Listed Successfully',
        '016' : 'Unable to Fetch Product'
    },
    "CLIENT": {
        '001': 'Missing Mandate Fields to Insert',
        '002': 'Missing Mandate Fields to Get',
        '003': 'Missing Mandate Fields to List',
        '004': 'Missing Mandate Fields to Fetch By Partners',
        '005': 'Missing Mandate Fields to Remove',
        '007' : 'Clients Inserted Successfully',
        '008' : 'Unable to Insert Clients',
        '009' : 'Clients Fetched Successfully',
        '010' : 'Unable to Fetch Clients',
        '011' : 'Clients Fetched by Partners Info',
        '012' : 'Unable to fetch Clients by Partners Info',
        '013' : 'Clients Removed Successfully',
        '014' : 'Unable to Remove Product',
        '015' : 'Clients Listed Successfully',
        '016' : 'Unable to Fetch Clients'
    },
    "CATEGORIES": {
        '001': 'Missing Mandate Fields to Insert',
        '002': 'Missing Mandate Fields to Get',
        '003': 'Missing Mandate Fields to List',
        '004': 'Missing Mandate Fields to Fetch By Companies',
        '005': 'Missing Mandate Fields to Remove',
        '007' : 'Categories Inserted Successfully',
        '008' : 'Unable to Insert Category',
        '009' : 'Categories Fetched Successfully',
        '010' : 'Unable to Fetch Categories',
        '011' : 'Categories Fetched by Company Info',
        '012' : 'Unable to fetch Categories by Company Info',
        '013' : 'Categories Removed Successfully',
        '014' : 'Unable to Remove Categories',
        '015' : 'Categories Listed Successfully',
        '016' : 'Unable to Fetch Categories'
    },
    "INTEREST": {
        '001': 'Missing Mandate Fields to Insert',
        '002': 'Missing Mandate Fields to Get',
        '003': 'Missing Mandate Fields to List',
        '004': 'Missing Mandate Fields to Fetch By Partners',
        '005': 'Missing Mandate Fields to Remove',
        '007' : 'Interest Inserted Successfully',
        '008' : 'Unable to Insert Category',
        '009' : 'Interest Fetched Successfully',
        '010' : 'Unable to Fetch Categories',
        '011' : 'Interest Fetched by Company Info',
        '012' : 'Unable to fetch Interest by Partners Info',
        '013' : 'Interest Removed Successfully',
        '014' : 'Unable to Remove Categories',
        '015' : 'Interest Listed Successfully',
        '016' : 'Unable to Fetch Interest'
    },
    "CLIENTS": {
        '001': 'Missing Mandate Fields to Insert',
        '002': 'Missing Mandate Fields to Get',
        '003': 'Missing Mandate Fields to List',
        '004': 'Missing Mandate Fields to Fetch By Partners',
        '005': 'Missing Mandate Fields to Remove',
        '007' : 'Clients Inserted Successfully',
        '008' : 'Unable to Insert Clients',
        '009' : 'Clients Fetched Successfully',
        '010' : 'Unable to Fetch Clients',
        '011' : 'Clients Fetched by Partners Info',
        '012' : 'Unable to fetch Clients by Partners Info',
        '013' : 'Clients Removed Successfully',
        '014' : 'Unable to Remove Clients',
        '015' : 'Clients Listed Successfully',
        '016' : 'Unable to Fetch Clients'
    },
    "PROFILE": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Update',
        '003': 'Missing Mandatory Fields while User',
        '004': 'Problem while saving and creating a Profile',
        '005': 'Fetching a Profile for an User',
        '006': 'Problem while saving and Updating a Profile',
        '007': 'Profile Created Successfully',
        '008': 'Profile Updated Successfully'
    },
    "COMPANIES": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while List',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Remove',
        '006': 'Missing Mandatory Fields while set Interest',
        '007': 'Register completed successfully',
        '017': 'Registered Companies Fetched Successfully',
        '018': 'You do not have any companies Registered',
        '019': 'Companies Updated Successfully',
        '020': 'Error while updating Company',
        '021': 'Mail Sent Completely',
        '022': 'Domain name already exists'
    },
    "PARTNERS": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while List',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Remove',
        '006': 'Missing Mandatory Fields while set Interest',
        '007': 'Register completed successfully',
        '017': 'Registered Partners Fetched Successfully',
        '018': 'You do not have any partners Registered',
        '019': 'Partners Updated Successfully',
        '020': 'Error while updating Partners',
        '021': 'Mail Sent Completely',
        '022': 'Domain name already exists'
    },
    "INVESTMENT": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while List',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Remove',
        '006': 'Missing Mandatory Fields while set Interest',
        '017': 'Registered Investments Fetched Successfully'
    },
    "DOMAIN": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while List',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Remove',
        '006': 'Yet to Configure Domain name',
        '016': 'Yet to Configure Domain name',
        '017': 'Registered Domain Fetched Successfully'
    },
    "PURCHASE": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Updating',
        '006': 'Purchase Status updated Successfully',
        '007': 'Error While Updating Purchase',
        '011': 'Purchase History Fetched Successfully',
        '012': 'Error While doing Purchase History',
        '013': 'Fee Configuration returned Successfully',
        '014': 'Purchase Updated Successfully',
        '015': 'Error While Updating the Purchase'
    },
    "REDEEM": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '004': 'Missing Mandatory Fields while Get By User',
        '011': 'Redeem details fetched Successfully'
    },
    "SHARES": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Update',
        '006': 'Missing Mandatory Fields while Update Count',
        '007': 'Shares has been updated Successfully',
        '013': 'Fee Configuration returned Successfully',
        '019': 'Missing Mandatory Fields while Get By Company',
        '020': 'Share Information fetched Successfully',
        '021': 'Error while Fetching Share information by company',
        '022': 'Share Information fetched Successfully',
        '023': 'Error while Fetching Share information by Investment',
        '024': 'Share Transfer Completed Successfully',
        '025': 'Error While Transferring Shares',
        '083': 'Transfer is setting it up. Try Submitting again 2 mins'
    },
    "TRANSACTION": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '004': 'Missing Mandatory Fields while Get By User'
    },
    "WALLET": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Update',
        '006': 'Missing Mandatory Fields while Fetching History',
        '017': 'Wallet History fetched Successfully',
        '018': 'Error while fetching Wallet History Successfully'
    },
    "PROPOSAL": {
        '001': 'Missing Mandatory Fields while Inserting',
        '002': 'Missing Mandatory Fields while Get',
        '003': 'Missing Mandatory Fields while List',
        '004': 'Missing Mandatory Fields while Get By User',
        '005': 'Missing Mandatory Fields while Remove',
        '007': 'Proposal Created Successfully',
        '008': 'Error while creating Proposal',
        '009': 'Proposal Fetched Successfully',
        '010': 'Error while fetching Proposal',
        '011': 'Proposal By User Fetched Successfully',
        '012': 'Error while fetching Proposal By User',
        '013': 'Proposal Removed Successfully',
        '014': 'Error while Removing Proposal',
        '015': 'Proposal Fetched Successfully',
        '016': 'Error while fetching Proposal',
        '017': 'Missing Mandatory Fields while updating the Proposal',
        '018': 'Proposal Updated Successfully',
        '019': 'Error While Updating Proposal'
    }
};