export const INSERT_TRANSACTION_REQUEST = 'INSERT_TRANSACTION_REQUEST';
export const GET_TRANSACTION_REQUEST = 'GET_TRANSACTION_REQUEST';
export const USER_TRANSACTION_REQUEST = 'USER_TRANSACTION_REQUEST';

export const INSERT_TRANSACTION_SUCCESS = 'INSERT_TRANSACTION_SUCCESS';
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const USER_TRANSACTION_SUCCESS = 'USER_TRANSACTION_SUCCESS';
